version: 2
updates:
  - package-ecosystem: npm
    directory: "/" # package.json in root
    schedule:
      interval: "weekly"
    groups:
      npm-dependencies:
        patterns:
          - '*'
    commit-message:
      prefix: "npm"
    open-pull-requests-limit: 25
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
